language: node_js
node_js:
  - "8"
  - "9"
  - "10"
script:
  - yarn build

env:
  - DELAY_TOLERANCE=250

after_success: yarn coverage

notifications:
  email:
    on_success: never
    on_failure: always
